# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Build

on:
  push:
    branches:
      - v2/S7

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Deployment
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to Repositories
      run: ./gradlew publish
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORYURL }}
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORYUSER }}
        ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORYTOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Plugin
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus Plugin
        path: output/*-plugin.jar
    - name: Upload API
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus API
        path: output/*-API.jar
    - name: Upload Javadocs
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus Javadocs
        path: output/*-javadocs.jar
    - name: Upload Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: Release Notes
        path: output/*.md
